
export const Data: any[] = [
  {
    id:'1',
    name: 'Chocolate Cake',
    bakeTime: '10-20',
    price: 18000,
    favorite: true,
    desc: ['Italy '],
    stars: 4.5,
    imageUrl: 'baked-1.jpg',
    tags: ['FastFood', 'Brunch', 'Lunch'],
  },
  {
    id:'2',
    name: 'Macrons',
    price: 2000,
    bakeTime: '20-30',
    favorite: true,
    desc: [' persia ', ' middle east ', ' china '],
    stars: 4.7,
    imageUrl: 'baked-2.jpg',
    tags: ['SlowFood', 'Lunch', 'Sweets'],
  },
  {
    id:'3',
    name: 'Vanila cake',
    price: 10000,
    bakeTime: '10-15',
    favorite: false,
    desc: [' germany ', ' us '],
    stars: 3.5,
    imageUrl: 'baked-3.jpg',
    tags: ['FastFood', 'Sweets', 'Lunch'],
  },
  {
    id:'4',
    name: 'Banana Bread',
    price: 2000,
    bakeTime: '15-20',
    favorite: true,
    desc: [' belgium ', ' france '],
    stars: 3.3,
    imageUrl: 'baked-4.jpg',
    tags: ['Banana', 'Breakfast', 'Brunch'],
  },
  {
    id:'5',
    name: 'Coconut Bread',
    price: 2500,
    bakeTime: '30-45',
    favorite: false,
    desc: [' india ', ' asia '],
    stars: 3.0,
    imageUrl: 'baked-5.jpg',
    tags: ['Coconut Cravings', 'Breakfast'],
  },
  {
    id:'6',
    name: 'Chocolate Chip Cookies',
    price: 2000,
    bakeTime: '15-20',
    favorite: false,
    desc: [' italy '],
    stars: 4.0,
    imageUrl: 'baked-6.jpg',
    tags: ['FastFood', 'Snack', 'Lunch'],
  },
];